# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reposaur < Formula
  desc "Open source compliance tool for development platforms"
  homepage "https://reposaur.com"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reposaur/reposaur/releases/download/v0.7.1/reposaur_0.7.1_Darwin_arm64.tar.gz"
      sha256 "44de94e4b16ce14091c96d079cd956fe66d8d3a88c8119631f90b7ff6b2b61cb"

      def install
        bin.install "rsr"
        bash_completion.install "completions/rsr.bash" => "rsr"
        zsh_completion.install "completions/rsr.zsh" => "_rsr"
        fish_completion.install "completions/rsr.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reposaur/reposaur/releases/download/v0.7.1/reposaur_0.7.1_Darwin_x86_64.tar.gz"
      sha256 "c29fb39b880b05b955510a5a1a1f97d5cfe8531a383be4e2699f467555445c43"

      def install
        bin.install "rsr"
        bash_completion.install "completions/rsr.bash" => "rsr"
        zsh_completion.install "completions/rsr.zsh" => "_rsr"
        fish_completion.install "completions/rsr.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reposaur/reposaur/releases/download/v0.7.1/reposaur_0.7.1_Linux_arm64.tar.gz"
      sha256 "cdfd25928af7f29131fe8a7509a157b7f0ffb6223383e002984548923b07476c"

      def install
        bin.install "rsr"
        bash_completion.install "completions/rsr.bash" => "rsr"
        zsh_completion.install "completions/rsr.zsh" => "_rsr"
        fish_completion.install "completions/rsr.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reposaur/reposaur/releases/download/v0.7.1/reposaur_0.7.1_Linux_x86_64.tar.gz"
      sha256 "c936ad5461a2044c3cd563f5c91514d0a7f4ed117d514e06c219e41a901feb88"

      def install
        bin.install "rsr"
        bash_completion.install "completions/rsr.bash" => "rsr"
        zsh_completion.install "completions/rsr.zsh" => "_rsr"
        fish_completion.install "completions/rsr.fish"
      end
    end
  end

  test do
    system "#{bin}/rsr"
  end
end
