# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reposaur < Formula
  desc "The open source compliance tool for development platforms."
  homepage "https://reposaur.com"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reposaur/reposaur/releases/download/v0.7.0/reposaur_0.7.0_Darwin_arm64.tar.gz"
      sha256 "1543046c4a0fb801e0a5058cadb7b1973797ea911fb762c0a17aa7db6e06b241"

      def install
        bin.install "rsr"
        bash_completion.install "completions/rsr.bash" => "rsr"
        zsh_completion.install "completions/rsr.zsh" => "_rsr"
        fish_completion.install "completions/rsr.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reposaur/reposaur/releases/download/v0.7.0/reposaur_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "0080b53d9884b07ba3fcc93cd5b21d87c846875516e6f88446c973000dd0f8a5"

      def install
        bin.install "rsr"
        bash_completion.install "completions/rsr.bash" => "rsr"
        zsh_completion.install "completions/rsr.zsh" => "_rsr"
        fish_completion.install "completions/rsr.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reposaur/reposaur/releases/download/v0.7.0/reposaur_0.7.0_Linux_arm64.tar.gz"
      sha256 "fb7942194000421742b8755c33cb88ac24cd013ac146b445e451e2ebc22d5e37"

      def install
        bin.install "rsr"
        bash_completion.install "completions/rsr.bash" => "rsr"
        zsh_completion.install "completions/rsr.zsh" => "_rsr"
        fish_completion.install "completions/rsr.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reposaur/reposaur/releases/download/v0.7.0/reposaur_0.7.0_Linux_x86_64.tar.gz"
      sha256 "889ac4e477db8f2e23ec626f26712cc29781b1b5c8b424cf2c348f57aab614a1"

      def install
        bin.install "rsr"
        bash_completion.install "completions/rsr.bash" => "rsr"
        zsh_completion.install "completions/rsr.zsh" => "_rsr"
        fish_completion.install "completions/rsr.fish"
      end
    end
  end

  test do
    system "#{bin}/rsr --version"
  end
end
